services:

pipeline:
  build: &build-anchor
    image: docker:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -f Dockerfile -t local/pseudoglobals:${DRONE_COMMIT_SHA:0:7} .
    when:
      event: [push, tag]

  tests: &tests-anchor
    image: local/pseudoglobals:${DRONE_COMMIT_SHA:0:7}
    commands:
      - cd /go/src/app
      - make test
    environment:
    when:
      event: [push, tag]

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: tools-internal
    username: drone.globalwebindex.net
    icon_url: https://www.gcppodcast.com/images/post/droneio.png
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        <{{build.link}}|{{repo.name}}@{{build.branch}} *#{{build.number}}*> :+1: ({{since build.started}})
        *${DRONE_DEPLOY_TO} {{build.event}}* by *{{build.author}}*
      {{else}}
        <{{build.link}}|{{repo.name}}@{{build.branch}} *#{{build.number}}*> :boom: ({{since build.started}})
        *${DRONE_DEPLOY_TO} {{build.event}}* by *{{build.author}}*
      {{/success}}

