version: "3"
services:
  app:
    build: .
    command: make dev
    environment:
      - SHELL=/bin/sh
    volumes:
      - ./pseudoglobals/:/go/src/app/pseudoglobals/
      - ./examples/:/go/src/app/examples/
      - ./Makefile:/go/src/app/Makefile

